<?php

namespace AppBundle\Repository;

/**
 * FakturyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FakturyRepository extends \Doctrine\ORM\EntityRepository
{
}
