<?php

namespace AppBundle\Repository;

/**
 * KontrahenciFakturRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KontrahenciFakturRepository extends \Doctrine\ORM\EntityRepository
{
}
