<?php

namespace AppBundle\Repository;

/**
 * NaszeFirmyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NaszeFirmyRepository extends \Doctrine\ORM\EntityRepository
{
}
