<?php

namespace AppBundle\Repository;

/**
 * WyciagiBankoweRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperacjeRepository extends \Doctrine\ORM\EntityRepository
{
}
