<?php

namespace AppBundle\Repository;

/**
 * PodatkiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PodatkiRepository extends \Doctrine\ORM\EntityRepository
{
}
