<?php

namespace AppBundle\Repository;

/**
 * ProjektyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjektyRepository extends \Doctrine\ORM\EntityRepository
{
}
