# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    faktury_directory: '%kernel.root_dir%/../web/uploads/faktury'

services:
    app.manager.wyciagbankowy:
        class: AppBundle\Manager\WyciagBankowy
        arguments: ["@service_container"]
    faktury_uploader:
        class: AppBundle\Service\FileUploader
        arguments: ['%faktury_directory%']